Repository Team-Smeme/smeem-android, pull requests merged in 2023-06, with the labels that each got.

#23 App icon 적용
  app/src/main/AndroidManifest.xml
  app/src/main/ic_smeem-playstore.png
  app/src/main/res/drawable/ic_smeem_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_smeem.xml
  app/src/main/res/mipmap-anydpi-v26/ic_smeem_round.xml
  app/src/main/res/mipmap-hdpi/ic_smeem.png
  app/src/main/res/mipmap-hdpi/ic_smeem_foreground.png
  app/src/main/res/mipmap-hdpi/ic_smeem_round.png
  app/src/main/res/mipmap-mdpi/ic_smeem.png
  app/src/main/res/mipmap-mdpi/ic_smeem_foreground.png
  app/src/main/res/mipmap-mdpi/ic_smeem_round.png
  app/src/main/res/mipmap-xhdpi/ic_smeem.png
  app/src/main/res/mipmap-xhdpi/ic_smeem_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_smeem_round.png
  app/src/main/res/mipmap-xxhdpi/ic_smeem.png
  app/src/main/res/mipmap-xxhdpi/ic_smeem_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_smeem_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_smeem.png
  app/src/main/res/mipmap-xxxhdpi/ic_smeem_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_smeem_round.png
Labels: @z design

#22 플라밍고로 Version up
  app/build.gradle
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: Notification

#26 Authentication Setting for DataStore
  app/src/main/java/com/sopt/smeem/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/sopt/smeem/domain/model/auth/Authentication.kt
  app/src/main/java/com/sopt/smeem/domain/repository/AuthRepository.kt
Labels: Auth
