Repository Team-Smeme/smeem-android, pull requests merged in 2023-08, with the labels that each got.

#80 API 정비
  app/src/main/java/com/sopt/smeem/Anonymous.kt
  app/src/main/java/com/sopt/smeem/Authenticated.kt
  app/src/main/java/com/sopt/smeem/data/datasource/DiaryCommander.kt
  app/src/main/java/com/sopt/smeem/data/datasource/TrainingManager.kt
  app/src/main/java/com/sopt/smeem/data/datasource/UserModifier.kt
  app/src/main/java/com/sopt/smeem/data/model/request/DiaryRequest.kt
  app/src/main/java/com/sopt/smeem/data/model/request/UserInfoModifyingRequest.kt
  app/src/main/java/com/sopt/smeem/data/model/response/DiaryResponse.kt
  app/src/main/java/com/sopt/smeem/data/model/response/DiaryWritingResponse.kt
  app/src/main/java/com/sopt/smeem/data/model/response/MyPageResponse.kt
  app/src/main/java/com/sopt/smeem/data/model/response/TrainingGoalSimpleResponse.kt
  app/src/main/java/com/sopt/smeem/data/repository/DiaryRepositoryImpl.kt
  app/src/main/java/com/sopt/smeem/data/repository/TrainingRepositoryImpl.kt
  app/src/main/java/com/sopt/smeem/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/sopt/smeem/data/service/DiaryService.kt
  app/src/main/java/com/sopt/smeem/data/service/MyPageService.kt
  app/src/main/java/com/sopt/smeem/data/service/TrainingService.kt
  app/src/main/java/com/sopt/smeem/data/service/UserService.kt
  app/src/main/java/com/sopt/smeem/domain/model/AlarmEnabledDay.kt
  app/src/main/java/com/sopt/smeem/domain/model/Date.kt
  app/src/main/java/com/sopt/smeem/domain/model/RetrievedBadge.kt
  app/src/main/java/com/sopt/smeem/domain/model/TrainingGoalSimple.kt
  app/src/main/java/com/sopt/smeem/domain/repository/DiaryRepository.kt
  app/src/main/java/com/sopt/smeem/domain/repository/TrainingRepository.kt
  app/src/main/java/com/sopt/smeem/domain/repository/UserRepository.kt
  app/src/main/java/com/sopt/smeem/module/AnonymousModule.kt
  app/src/main/java/com/sopt/smeem/module/UserModule.kt
  app/src/main/java/com/sopt/smeem/presentation/join/JoinNicknameVM.kt
  app/src/main/java/com/sopt/smeem/presentation/join/JoinVM.kt
  app/src/main/java/com/sopt/smeem/presentation/mypage/BadgeViewModel.kt
  app/src/main/java/com/sopt/smeem/presentation/mypage/EditTrainingVM.kt
  app/src/main/java/com/sopt/smeem/presentation/mypage/MyPageVM.kt
  app/src/main/java/com/sopt/smeem/presentation/onboarding/OnBoardingActivity.kt
  app/src/main/java/com/sopt/smeem/presentation/onboarding/OnBoardingVM.kt
  app/src/main/java/com/sopt/smeem/presentation/splash/LoginVM.kt
Labels: !y help wanted

#81 MyPage 정비 ( 바뀐 API 대응 )
  app/src/main/java/com/sopt/smeem/data/model/response/MyPageResponse.kt
  app/src/main/java/com/sopt/smeem/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/sopt/smeem/domain/model/Badge.kt
  app/src/main/java/com/sopt/smeem/domain/model/BadgeType.kt
  app/src/main/java/com/sopt/smeem/module/UserModule.kt
  app/src/main/java/com/sopt/smeem/presentation/ImageBindingAdapter.kt
  app/src/main/java/com/sopt/smeem/presentation/home/HomeActivity.kt
  app/src/main/java/com/sopt/smeem/presentation/mypage/LanguagesAdaptor.kt
  app/src/main/java/com/sopt/smeem/presentation/mypage/MyBadgesActivity.kt
  app/src/main/java/com/sopt/smeem/presentation/mypage/MyPageActivity.kt
  app/src/main/java/com/sopt/smeem/presentation/mypage/MyPageVM.kt
  app/src/main/java/com/sopt/smeem/presentation/splash/SplashActivity.kt
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/item_my_page_language.xml
Labels: Auth

#86 자동 로그인 적용
  app/src/main/java/com/sopt/smeem/presentation/splash/LoginVM.kt
  app/src/main/java/com/sopt/smeem/presentation/splash/SplashActivity.kt
Labels: Auth

#146 일기 작성하기 버튼 로직 수정, 일기 불러오기 로직 수정
  app/src/main/java/com/sopt/smeem/presentation/calendar/WeeklyCalendarViewHolder.kt
  app/src/main/java/com/sopt/smeem/presentation/home/HomeActivity.kt
  app/src/main/java/com/sopt/smeem/presentation/home/HomeViewModel.kt
  app/src/main/res/layout/activity_home.xml
Labels: Calendar
